version: '3.8'

services:
  flask-webapp:
    build: ./python-apps/flask-webapp
    container_name: flask-webapp
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://myuser:mydbpassword@db:3306/mydb
      # Add other environment variables as needed
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mydbpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: